### ISSUE TITLE
Re-render the react tree to the content area instead of setting it to the content area.

### ISSUE THREAD

**Issue by treshugart** [skatejs/react-integration#2]
If we used a `content` property to "get" the content area, we could use that as the component we `ReactDOM.render()` to instead of rendering to an empty div and passing it to the `content` property. This would have the added benefits of `React` managing that diff tree.

**Comment by treshugart** [comment]
I suggest we continue to set the property with the React `props.children`, but only if we try and get the value of the `content` property and it's not a valid DOM element. This would allow for both scenarios to work.

**Comment by jpnelson** [comment]
Plan is to do this by rendering to the component directly, using named-slots polyfill and kickflip to get everything rendering correctly
