### ISSUE TITLE
Map web component event to react events using camel case convention

### ISSUE THREAD

**Issue by craigpetchell** [skatejs/react-integration#24]
Nice to have, but the react convention for event handler names in camel case, e.g. onClick, vs onclick for a web component.

It'd be nice to do this mapping automatically, so that the react component is consistent with how other react components work, so there's no surprises for consumers.

**Comment by treshugart** [comment]
In the referenced commit, I updated the tests to ensure that you can bind to `onClick` while handling a `click`. Same for `onCustomEvent` and `customevent`. Also clarified in the docs.

**Comment by craigpetchell** [comment]
So this already works - hmm... I must have been doing something wrong at the time. (oops)

**Comment by treshugart** [comment]
Maybe I just mis-interpreted. Feel free to reopen if I'm wrong :)
